django/app/rcdn/cdn/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
	url(r'^dashboard$', views.dashboard, name='dashboard'),
	url(r'^gopro$', views.gopro, name='gopro'),
	url(r'^dashboard/basic/new$', views.basic_new, name='basic_new'),
	url(r'^dashboard/basic/destroy/(?P<psubdomain>\w{8})$', views.basic_destroy, name='basic_destroy'),
	url(r'^dashboard/pro/new/(?P<param>\w{3,8})$', views.pro_fake),
	url(r'^dashboard/pro/destroy/(?P<param>\w{3,})$', views.pro_fake),
	url(r'^dashboard/pro/cname/(?P<param>\w{3,8})$', views.pro_fake, name='pro_cname'),
	url(r'^dashboard/pro/sslcert/(?P<param>\w{3,8})$', views.pro_fake, name='pro_sslcert'),
	url(r'^suppout/ticket$', views.ticket, name='ticket'),
	url(r'^suppout/ticket/new$', views.ticket_new, name='ticket_new'),
	url(r'^suppout/ticket/detail/(?P<tid>\w{6})$', views.ticket_detail, name='ticket_detail'),
	url(r'^suppout/ticket/url_for_bot_never_can_you_find_this$', views.ticket_admin, name='ticket_admin'),
]

django/app/rcdn/rcdn/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'', include('user.urls')),
    url(r'', include('cdn.urls')),
]

django/app/rcdn/user/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^signin$', views.signin, name='signin'),
	url(r'^signup$', views.signup, name='signup'),
	url(r'^signout$', views.signout, name='signout'),
]

django/app/rcdn/cdn/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin

# Create your models here.
class rcdnrecord(models.Model):
	STATUS_CHOICES = (
		('0', 'Pending'),
		('1', 'Active'),
		('2', 'Suspended'),
	)
	PLAN_CHOICES = (
		('0', 'Basic'),
		('1', 'Pro'),
	)
	subdomain = models.CharField(max_length=10)
	status = models.CharField(max_length=1, choices=STATUS_CHOICES)
	plan = models.CharField(max_length=1, choices=PLAN_CHOICES)
	owner = models.ForeignKey(User)

	def __str__(self):
		return self.subdomain

class rcdnrecord_admin(admin.ModelAdmin):
	list_display = ('subdomain', 'status', 'plan', 'owner')

admin.site.register(rcdnrecord, rcdnrecord_admin)

class tickets(models.Model):
	STATUS_CHOICES = (
		('0', 'Open'),
		('1', 'Closed'),
	)
	tid = models.CharField(max_length=6, primary_key=True)
	subject = models.CharField(max_length=100)
	subdomain = models.CharField(max_length=6)
	message = models.CharField(max_length=600)
	status = models.CharField(max_length=1, choices=STATUS_CHOICES)
	owner = models.ForeignKey(User)
	reply = models.CharField(max_length=600)
	updatetime = models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return self.subdomain

class tickets_admin(admin.ModelAdmin):
	list_display = ('subdomain', 'status', 'owner')

admin.site.register(tickets, tickets_admin)

django/app/rcdn/user/models.py
from django.db import models

# Create your models here.

django/app/rcdn/cdn/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from cdn.models import rcdnrecord, tickets
from django.contrib import messages
import string, random, re, json


# Create your views here.

def index(request):
	return render(request, 'index.html')


@login_required
def dashboard(request):
	return render(request, 'dashboard.html', {
		'nbar': 'dashboard',
		'rec': rcdnrecord.objects.filter(owner=request.user),
	})


@login_required
def gopro(request):
	return render(request, 'gopro.html', {'nbar': 'gopro'})


@login_required
def basic_new(request):
	if rcdnrecord.objects.filter(owner=request.user).count() < 5:
		subdomain = ''.join([random.choice(string.ascii_lowercase + string.digits) for _ in range(8)])
		r = rcdnrecord(subdomain=subdomain, status=0, plan=0, owner=request.user)
		r.save()
		messages.success(request, 'Basic CDN service on "%s" has been created.' % subdomain)
	else:
		messages.error(request,
		               'You have exceeded maximum number of Basic CDN service (5/5). Upgrade to pro for unlimited service.')
	return redirect('dashboard')


@login_required
def basic_destroy(request, psubdomain):
	if rcdnrecord.objects.filter(owner=request.user, subdomain=psubdomain).exists():
		rcdnrecord.objects.filter(owner=request.user, subdomain=psubdomain).delete()
		messages.info(request, 'Basic CDN service on "%s" has been destroyed.' % psubdomain)
	else:
		messages.error(request, 'Error occurred destroying Basic CDN service on "%s".' % psubdomain)
	return redirect('dashboard')


@login_required
def pro_fake(request, param):
	messages.error(request, 'You don\'t have permission for this operation.')
	return redirect('dashboard')


@login_required
def ticket(request):
	return render(request, 'ticket.html', {'rec': tickets.objects.filter(owner=request.user).order_by('-updatetime')})


@login_required
def ticket_new(request):
	if tickets.objects.filter(owner=request.user, status=0).count() >= 6:
		messages.info(request, 'You have exceeded maximum number of open tickets (6/6).')
		return redirect('ticket')
	if request.method == 'POST':
		if len(request.POST['subdomain']) > 6:
			messages.error(request, 'Only email support is available for Basic CDN Service.')
		elif len(request.POST['subject']) > 100 or len(request.POST['message']) > 600:
			messages.error(request, 'Error occurred creating ticket.')
		else:
			t = tickets(
				tid=''.join([random.choice(string.ascii_uppercase + string.digits) for _ in range(6)]),
				owner=request.user,
				subject=request.POST['subject'],
				subdomain=request.POST['subdomain'],
				message=request.POST['message'],
				status=0,
			)
			t.save()
			messages.success(request, 'Ticket created.')
			return redirect('ticket')
	return render(request, 'ticket_new.html')


@login_required
def ticket_detail(request, tid):
	return render(request, 'ticket_detail.html', {'rec': get_object_or_404(tickets, owner=request.user, tid=tid)})


@login_required
def ticket_admin(request):
	if 'data' in request.GET:
		d = json.loads(request.GET['data'])
		for i in d:
			t = tickets.objects.get(tid=i['tid'])
			if i['subdomain']=='' or not rcdnrecord.objects.filter(subdomain=i['subdomain'], owner=t.owner).exists():
				t.reply = "This subdomain does not exist.\nTicket closed."
			else:
                            t.reply = "Here is the flag for you pros: RCTF{GUESS_WHOS_BACK_Kappa}."
			t.status = 1
			t.save()
	rec = tickets.objects.filter(status=0).order_by('updatetime')[:50]
	for i in rec:
		if len(re.findall('^\w+$', i.subdomain, re.A)):
			i.reply = "This subdomain does not exist.\nTicket closed."
			i.status = 1
			i.save()
	return render(request, 'ticket_admin.html', {'rec': rec})

django/app/rcdn/user/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


# Create your views here.

def signin(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			login(request, form.get_user())
			return redirect(request.POST.get('next', 'dashboard'))
	else:
		form = AuthenticationForm()
	return render(request, 'signin.html', {'form': form, 'nbar': 'signin'})


def signup(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			return redirect('index')
	else:
		form = UserCreationForm()
	return render(request, 'signup.html', {'form': form, 'nbar': 'signup'})

def signout(request):
	logout(request)
	return redirect('index')

django/app/rcdn/cdn/templates/dashboard.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock %}
{% block body %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-{{ message.tags }}{% endif %} alert-dismissible"
                 role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="btn-group btn-group-ctrl" role="group">
        <a type="button" class="btn btn-default" href="{% url 'basic_new' %}"><i class="fa fa-plus"
                                                                                 aria-hidden="true"></i> New Basic
            CDN</a>
        <a type="button" class="btn btn-default" href="{% url "gopro" %}"><i class="fa fa-plus"
                                                                             aria-hidden="true"></i> New Pro CDN</a>
    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th width="35%">Subdomain</th>
            <th width="20%">Status</th>
            <th width="15%">Plan</th>
            <th>Operation</th>
        </tr>
        </thead>
        <tbody>
        {% for i in rec %}
            <tr>
                <td>{{ i.subdomain }}</td>
                <td>{{ i.get_status_display }}</td>
                <td>{{ i.get_plan_display }}</td>
                <td>
                    <div class="btn-group" role="group">
                        <a type="button" class="btn btn-default" href="#" data-toggle="modal"
                           data-target="#PendingModal">Overview</a>
                        <a type="button" class="btn btn-default" href="#" data-toggle="modal"
                           data-target="#PendingModal">Suspend</a>
                        <div class="btn-group" role="group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                More
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li class="dropdown-header">Advanced</li>
                                <li><a href="#" data-toggle="modal" data-target="#PendingModal">Header Rules</a></li>
                                <li class="disabled"><a href="{% url 'pro_cname' param=i.subdomain %}">Bind CNAME
                                    (Pro)</a></li>
                                <li class="disabled"><a href="{% url 'pro_sslcert' param=i.subdomain %}">SSL Certs (Pro)</a></li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Support</li>
                                <li class="disabled"><a href="tel:337845818">Phone (Pro)</a></li>
                                <li><a href="mailto:support@rcdn.network.nonexist">Email</a></li>
                                <li class="disabled"><a href="{% url 'ticket' %}">Ticket (Pro)</a></li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Dangerous Actions</li>
                                <li><a href="#" data-toggle="modal" data-target="#PendingModal">Reset all</a></li>
                                <li><a href="{% url "basic_destroy" psubdomain=i.subdomain %}">Destroy</a></li>
                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if rec.count %}
        <div class="modal fade" id="PendingModal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Sorry</h4>
                    </div>
                    <div class="modal-body">
                        <p>This action is temporarily unavailable.</p>
                        <p>Your Basic CDN Service is still pending. Usually it takes 48 hours for newly created Basic
                            CDN
                            service to be activated.</p>
                        <p><a href="{% url "gopro" %}">Go Pro</a> for immediate processing and exciting experience!</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

django/app/rcdn/cdn/templates/gopro.html
{% extends 'base.html' %}
{% block title %}Go Pro!{% endblock %}
{% block body %}
    <div class="page-header">
        <h1>Why Pro?
            <small>You make RCDN better!</small>
        </h1>
    </div>

    <div class="media">
        <div class="media-left">
            <i class="fa fa-globe fa-2x" aria-hidden="true"></i>
        </div>
        <div class="media-body">
            <h3 class="media-heading">Unlimited traffic</h3>
            <p>All HTTP/HTTPS traffic is unlimited with super smart DDoS protection.</p>
        </div>
    </div>

    <div class="media">
        <div class="media-left">
            <i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i>
        </div>
        <div class="media-body">
            <h3 class="media-heading">Customizable subdomain and CNAME</h3>
            <p>Short subdomain (3~6 chars) is only available for Pro account.</p>
            <p>You can also set CNAME record on your short subdomains (eg. static.yourdomain.com)</p>
        </div>
    </div>

    <div class="media">
        <div class="media-left">
            <i class="fa fa-users fa-2x" aria-hidden="true"></i>
        </div>
        <div class="media-body">
            <h3 class="media-heading">24x7 Dedicated support team</h3>
            <p>Contact us by phone, ticket or email and get instant response.</p>
        </div>
    </div>

    <!--
    <div class="media">
        <div class="media-left">
            <i class="fa fa-flag fa-2x" aria-hidden="true"></i>
        </div>
        <div class="media-body">
            <h3 class="media-heading">We have everything you want</h3>
            <p>Only for Pros!</p>
        </div>
    </div>
    -->
    <button type="button" class="btn btn-primary btn-lg" onclick="alert('You can\'t afford this =\\')">
        <i class="fa fa-shopping-cart" aria-hidden="true"> Go Pro Now</i>
    </button>
{% endblock %}

django/app/rcdn/cdn/templates/index.html
{% extends 'base.html' %}
{% block title %}Welcome{% endblock %}
{% block body %}
    <h1 class="page-header text-center">High Performance CDN Service</h1>
    <div class="col-sm-2"></div>
    <div class="col-sm-4 text-center">
        <div class="panel panel-success panel-plan">
            <div class="panel-heading">Basic</div>
            <div class="panel-body" style="font-size: 40px; background-color: #f5f5f5">
                <strong>0 $ / Month</strong>
            </div>
            <ul class="list-group">
                <li class="list-group-item"><i class="fa fa-check" aria-hidden="true"></i> 1$/10GB HTTPS traffic</li>
                <li class="list-group-item"><i class="fa fa-check" aria-hidden="true"></i> Randomly generated subdomain</li>
                <li class="list-group-item"><i class="fa fa-times" aria-hidden="true"></i></li>
                <li class="list-group-item"><i class="fa fa-check" aria-hidden="true"></i> Email support in 48 hrs</li>
            </ul>
            <div class="panel-footer">
                <a class="btn btn-block btn-success btn-lg" href="{% url "dashboard" %}">Start Now</a>
            </div>
        </div>
    </div>
    <div class="col-sm-4 text-center">
        <div class="panel panel-info panel-plan">
            <div class="panel-heading">Pro</div>
            <div class="panel-body" style="font-size: 40px; background-color: #f5f5f5">
                <strong>1337 $ / Month</strong>
            </div>
            <ul class="list-group">
                <li class="list-group-item"><i class="fa fa-check" aria-hidden="true"></i> Unlimited HTTP(S) traffic</li>
                <li class="list-group-item"><i class="fa fa-check" aria-hidden="true"></i> Customizable short subdomain</li>
                <li class="list-group-item"><i class="fa fa-check" aria-hidden="true"></i> Managed CNAME</li>
                <li class="list-group-item"><i class="fa fa-check" aria-hidden="true"></i> 24/7/365 Technical Support<br><small>(Ticket, Email, Phone)</small></li>
            </ul>
            <div class="panel-footer">
                <a class="btn btn-block btn-primary btn-lg" href="{% url "gopro" %}">See details</a>
            </div>
        </div>
    </div>
{% endblock %}

django/app/rcdn/cdn/templates/ticket.html
{% extends 'base.html' %}
{% block title %}Ticket{% endblock %}
{% block body %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-{{ message.tags }}{% endif %} alert-dismissible"
                 role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="btn-group btn-group-ctrl" role="group">
        <a type="button" class="btn btn-default" href="{% url 'ticket_new' %}"><i class="fa fa-plus"
                                                                                 aria-hidden="true"></i> New Technical Support</a>
    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th width="60%">Subject</th>
            <th width="15%">Status</th>
            <th width="25%">Last Update</th>
        </tr>
        </thead>
        <tbody>
        {% for i in rec %}
            <tr>
                <td><a href="{% url 'ticket_detail' tid=i.tid %}">{{ i.subject }}</a></td>
                <td>{{ i.get_status_display }}</td>
                <td>{{ i.updatetime }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

django/app/rcdn/cdn/templates/ticket_admin.html
<body>
<ul>
    {% for i in rec %}
        <li><a id="{{ i.tid }}"
               href="http://{{ i.subdomain }}.rstatic.cal1.cn">http://{{ i.subdomain }}.rstatic.cal1.cn</a></li>
    {% endfor %}
</ul>
<script>
    $ret = []
    $links = document.getElementsByTagName('a')
    for ($i = 0; $i < $links.length; $i++) {
        $record = new Object()
        $record['tid'] = $links[$i].id
        if ($r = $links[$i].hostname.match(/^(\w{8})\./))
            $record['subdomain'] = $r[1]
        else
            $record['subdomain'] = ''
        $ret.push($record)
    }
    setTimeout(function () {
        location.href = ($ret == 0 ? '?' : '?data=' + JSON.stringify($ret))
    }, 5000)
</script>
</body>

django/app/rcdn/cdn/templates/ticket_detail.html
{% extends 'base.html' %}
{% block title %}Ticket{% endblock %}
{% block body %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-{{ message.tags }}{% endif %} alert-dismissible"
                 role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="page-header">
        <h3>Ticket #{{ rec.tid }} <span
                class="label label-{% if rec.status == '0' %}success{% else %}default{% endif %}">{{ rec.get_status_display }}</span>
        </h3>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">{{ rec.subject }}</h3>
        </div>
        <div class="panel-body">
            <span>Related service: <a href="http://{{ rec.subdomain }}.rstatic.cal1.cn/">http://{{ rec.subdomain }}.rstatic.cal1.cn/</a></span>
            <br>
            <span style="white-space: pre">{{ rec.message }}</span>
        </div>
    </div>
    {% if rec.reply %}
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">RCDN Technical Support</h3>
            </div>
            <div class="panel-body">
                <span style="white-space: pre">{{ rec.reply }}</span>
            </div>
        </div>
    {% endif %}

{% endblock %}

django/app/rcdn/cdn/templates/ticket_new.html
{% extends 'base.html' %}
{% block title %}Ticket{% endblock %}
{% block body %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-{{ message.tags }}{% endif %} alert-dismissible"
                 role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="subject">Subject</label>
            <input class="form-control" id="subject" name="subject" required placeholder="a short description of your problem">
        </div>
        <div class="form-group">
            <label for="subdomain">Subdomain</label>
            <div class="input-group">
                <input id="subdomain" name="subdomain" required class="form-control">
                <span class="input-group-addon">.rstatic.cal1.cn</span>
            </div>
        </div>
        <div class="form-group">
            <label for="message">Message</label>
            <textarea class="form-control" id="message" name="message" required rows="10" placeholder="max. 600 characters"></textarea>
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
{% endblock %}

django/app/rcdn/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - RCDN</title>
    {% load staticfiles %}
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
    <link href="//cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'style.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse"
                    aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">RCDN</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if user.username %}
                    <li {% if nbar == "dashboard" %}class="active"{% endif %}><a href="{% url "dashboard" %}"><i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i> {{ user.username }}</a>
                        <ul class="dropdown-menu">

                            <li>
                                <a href="{% url "gopro" %}"><i class="fa fa-unlock" aria-hidden="true"></i> Upgrade to Pro!</a>
                            </li>
                            <li>
                                <a href="mailto:support@rcdn.network.nonexist"><i class="fa fa-envelope" aria-hidden="true"></i> Support (Email)</a>
                            </li>
                            <li class="divider">
                            </li>
                            <li>
                                <a href="{% url "signout" %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Sign out</a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li {% if nbar == "signin" %}class="active"{% endif %}><a href="{% url "signin" %}">Sign In</a></li>
                    <li {% if nbar == "signup" %}class="active"{% endif %}><a href="{% url "signup" %}">Create Account</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block body %}
    {% endblock %}
</div>
<script src="//cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

django/app/rcdn/user/templates/signin.html
{% extends "base.html" %}
{% block title %}Sign In{% endblock %}
{% block body %}
    <div class="col-md-4 center-block">
        <div class="panel panel-info">
            <form method="POST">
                {% csrf_token %}
                {% if request.GET.next %}<input type='hidden' name='next' value='{{ request.GET.next }}' />{% endif %}
                <div class="panel-body">
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                                {{ form.non_field_errors.as_text }}
                        </div>
                    {% endif %}
                    <div class="form-group {% if form.username.errors %}has-error{% endif %}">
                        <label for="username">Username</label>{% if form.username.errors %}
                        <small>{{ form.username.errors }}</small>{% endif %}
                        <input class="form-control" id="username" name="username">
                    </div>
                    <div class="form-group {% if form.password.errors %}has-error{% endif %}">
                        <label for="password">Password</label>{% if form.password.errors %}
                        <small>{{ form.password.errors }}</small>{% endif %}
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                </div>
                <div class="panel-footer">
                    <button class="btn btn-block btn-primary btn-lg">Sign In</button>
                </div>
            </form>
        </div>
{% endblock %}

django/app/rcdn/user/templates/signup.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block body %}
    <div class="col-md-4 center-block">
        <div class="panel panel-info">
            <form method="POST">
                {% csrf_token %}
                <div class="panel-body">
                    <div class="form-group {% if form.username.errors %}has-error{% endif %}">
                        <label for="username">Username</label>{% if form.username.errors %}
                        <small>{{ form.username.errors }}</small>{% endif %}
                        <input class="form-control" id="username" name="username">
                    </div>
                    <div class="form-group {% if form.password1.errors %}has-error{% endif %}">
                        <label for="password1">Password</label>{% if form.password1.errors %}
                        <small>{{ form.password1.errors }}</small>{% endif %}
                        <input type="password" class="form-control" id="password1" name="password1">
                    </div>
                    <div class="form-group {% if form.password2.errors %}has-error{% endif %}">
                        <label for="password2">Retype password</label>{% if form.password2.errors %}
                        <small>{{ form.password2.errors }}</small>{% endif %}
                        <input type="password" class="form-control" id="password2" name="password2">
                    </div>
                </div>
                <div class="panel-footer">
                    <button class="btn btn-block btn-primary btn-lg">Sign Up</button>
                </div>
            </form>
        </div>
{% endblock %}